openapi: 3.0.0
info:
  title: URL Content Extraction and RAG System API
  version: 1.0.0
  description: API for extracting content from URLs, generating embeddings, and storing in vector database

paths:
  /extract-website:
    post:
      summary: Extract content from all pages of a website
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                base_url:
                  type: string
                  description: The base URL of the website to extract content from
                  example: "https://example.com"
                collection_name:
                  type: string
                  description: Name of the Qdrant collection to store content in
                  example: "website_content"
                chunk_size:
                  type: integer
                  description: Size of text chunks in characters
                  default: 1000
                chunk_overlap:
                  type: integer
                  description: Overlap between chunks in characters
                  default: 100
      responses:
        '200':
          description: Successfully processed the website
          content:
            application/json:
              schema:
                type: object
                properties:
                  pages_processed:
                    type: integer
                    description: Number of pages successfully processed
                  chunks_stored:
                    type: integer
                    description: Number of content chunks stored in the database
                  errors:
                    type: integer
                    description: Number of pages that failed to process
        '400':
          description: Invalid input parameters
        '500':
          description: Internal server error during processing

  /extract-url:
    post:
      summary: Extract content from a specific URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The URL to extract content from
                  example: "https://example.com/page"
                collection_name:
                  type: string
                  description: Name of the Qdrant collection to store content in
                  example: "website_content"
      responses:
        '200':
          description: Successfully extracted and stored content
          content:
            application/json:
              schema:
                type: object
                properties:
                  chunks_stored:
                    type: integer
                    description: Number of content chunks stored in the database
                  source_url:
                    type: string
                    description: The URL that was processed
                  content_length:
                    type: integer
                    description: Length of extracted content in characters
        '400':
          description: Invalid URL or parameters
        '500':
          description: Internal server error during processing

  /search:
    post:
      summary: Search for content using semantic similarity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The search query text
                  example: "information about AI in robotics"
                collection_name:
                  type: string
                  description: Name of the Qdrant collection to search in
                  example: "website_content"
                limit:
                  type: integer
                  description: Maximum number of results to return
                  default: 5
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        text:
                          type: string
                          description: The matching text content
                        source_url:
                          type: string
                          description: URL where the content was found
                        similarity_score:
                          type: number
                          description: Similarity score between 0 and 1
        '400':
          description: Invalid search parameters
        '500':
          description: Internal server error during search